# Generated by Django 4.0.8 on 2022-11-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataset3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cancellationDate',
            new_name='cancellation_date',
        ),
    ]
