# Generated by Django 4.0.8 on 2022-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('publisher1', models.CharField(max_length=200)),
                ('publisher2', models.CharField(max_length=200)),
                ('releaseDate1', models.CharField(max_length=200)),
                ('releaseDate2', models.CharField(max_length=200)),
            ],
        ),
    ]
