# Generated by Django 4.0.8 on 2022-11-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataset1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSet1',
            new_name='Game',
        ),
    ]
